name: Build Next.js
on: [push]
jobs:
  build_next:
    runs-on: ubuntu-latest
    name: Build Next.js
    steps:
    - uses: actions/checkout@v3
    - id: Build-Next
      uses: ricardobiundo/NextPagesAction@1.0.2
      with:
        username: 'Mazharcodemaster'
        reponame: 'chat'
        token: ${{ secrets.TOKEN }} # Leave this line unchanged
