name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    # List contents of the .next directory to ensure files exist
    - name: List build directory contents
      run: ls -la ./.next

    - name: Upload production-ready files
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./.next

  deploy:
    name: Deploy Project
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./.next

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./.next
